version: '3'
services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - CLIENT_TOKEN=${CLIENT_TOKEN}
    volumes:
      - .:/app
    ports:
      - "5000:5000"  # Adjust port mappings as needed

